package rs.ac.singidunum.tf.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import rs.ac.singidunum.tf.entities.Zaduzenje;
import rs.ac.singidunum.tf.repository.ZaduzenjeRepository;;

@RestController
@RequestMapping
public class ZaduzenjeController {
	
	@Autowired // This means to get the bean called repository
    // Which is auto-generated by Spring, we will use it to handle the data
	private ZaduzenjeRepository repository;
	
	public ZaduzenjeController(ZaduzenjeRepository repository) {
		this.repository = repository;
	}
	
	@CrossOrigin
	@GetMapping("/zaduzenje")
	public @ResponseBody Iterable<Zaduzenje> getAll(){
		// This returns a JSON or XML with the books
		return repository.findAll();
	}
	
	@CrossOrigin
	@GetMapping("/zaduzenje/{id}")
	public Zaduzenje getZaduzenje(@PathVariable Integer id) {
		return repository.findById(id).orElse(null); 
	}
	
	@CrossOrigin
	@PostMapping("/zaduzenje")
	public Zaduzenje createZaduzenje(@RequestBody Zaduzenje zaduzenje) {
		return repository.save(zaduzenje);
	}
	
	@CrossOrigin
	@DeleteMapping("/zaduzenje/{id}")
	public boolean deleteZaduzenje(@PathVariable Integer id) {
		repository.deleteById(id);
		return true;
	}
	
	@CrossOrigin
	@PutMapping("/zaduzenje/{id}")
	public Zaduzenje updateZaduzenje(@PathVariable Integer id, @RequestBody Zaduzenje zaduzenje) {
		return repository.save(zaduzenje);
	}
	
}
